timeout: 0

/ruos
    protocol: limine
    path: boot():/boot/kernel
    module_path: boot():/init.wasm
    module_cmdline: /init.wasm
    module_path: boot():/server.wasm
    module_cmdline: /server.wasm
    module_path: boot():/client.wasm
    module_cmdline: /client.wasm
