//! Password verification with two backing stores:
//!
//! 1. `/mnt/passwd` (preferred when present): PBKDF2-HMAC-SHA256 hash, format
//!    `pbkdf2-sha256:<iterations>:<salt-hex>:<hash-hex>`. Generated by
//!    `make passwd-on-disk` or seeded by the default `make disk` rule.
//! 2. Compile-time default: plaintext password baked at build time via
//!    `RUOS_DEFAULT_PASSWORD` env var (defaults to `ruos`). Used when no
//!    disk is attached or `/mnt/passwd` is missing/unparseable, so a fresh
//!    ISO boot has working SSH out of the box.
//!
//! The plaintext fallback is intentionally weak — it lives in the kernel
//! binary, visible to anyone with the ISO. It's a demo-OS convenience, not a
//! security mechanism. Override with `/mnt/passwd` for a real hash.

use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;
use sha2::Sha256;

use crate::vfs::{block_on, OpenFlags};

/// Compile-time default password. Overridden by `RUOS_DEFAULT_PASSWORD` at
/// build time. Empty string = password auth disabled in the fallback path
/// (only `/mnt/passwd` will work).
const DEFAULT_PASSWORD: &str = match option_env!("RUOS_DEFAULT_PASSWORD") {
    Some(s) => s,
    None    => "ruos",
};

pub enum PasswordCheck {
    Pbkdf2(Pbkdf2Hash),
    Plaintext(&'static str),
}

pub struct Pbkdf2Hash {
    iterations: u32,
    salt:       Vec<u8>,
    hash:       Vec<u8>,
}

/// Returns the active password check. Always `Some` unless the build-time
/// default is empty AND no parseable `/mnt/passwd` exists.
pub fn load(path: &str) -> Option<PasswordCheck> {
    if let Some(h) = load_pbkdf2(path) {
        return Some(PasswordCheck::Pbkdf2(h));
    }
    if !DEFAULT_PASSWORD.is_empty() {
        crate::binfo!(
            "ssh",
            "password fallback to built-in default (set RUOS_DEFAULT_PASSWORD or seed {})",
            path
        );
        return Some(PasswordCheck::Plaintext(DEFAULT_PASSWORD));
    }
    crate::bwarn!("ssh", "password auth disabled (no {} and no built-in default)", path);
    None
}

/// Constant-time verify against the configured check.
pub fn verify(password: &str, check: &PasswordCheck) -> bool {
    match check {
        PasswordCheck::Pbkdf2(h)    => verify_pbkdf2(password, h),
        PasswordCheck::Plaintext(p) => ct_eq(password.as_bytes(), p.as_bytes()),
    }
}

fn verify_pbkdf2(password: &str, h: &Pbkdf2Hash) -> bool {
    let mut out = vec![0u8; h.hash.len()];
    pbkdf2::pbkdf2_hmac::<Sha256>(password.as_bytes(), &h.salt, h.iterations, &mut out);
    ct_eq(&out, &h.hash)
}

fn load_pbkdf2(path: &str) -> Option<Pbkdf2Hash> {
    let raw = read_to_string(path)?;
    let line = raw.lines().find(|l| {
        let t = l.trim();
        !t.is_empty() && !t.starts_with('#')
    })?;
    let parsed = parse(line.trim());
    if parsed.is_none() {
        crate::bwarn!("ssh", "{}: unparseable password line", path);
    } else {
        crate::binfo!("ssh", "loaded password hash from {}", path);
    }
    parsed
}

fn parse(line: &str) -> Option<Pbkdf2Hash> {
    let mut it = line.splitn(4, ':');
    if it.next()? != "pbkdf2-sha256" { return None; }
    let iterations: u32 = it.next()?.parse().ok()?;
    if iterations < 1_000 { return None; }
    let salt = hex_decode(it.next()?)?;
    let hash = hex_decode(it.next()?)?;
    if salt.is_empty() || hash.len() != 32 { return None; }
    Some(Pbkdf2Hash { iterations, salt, hash })
}

fn read_to_string(path: &str) -> Option<String> {
    let fd = block_on(crate::vfs::open(path, OpenFlags::READ)).ok()?;
    let mut buf = vec![0u8; 512];
    let n = block_on(crate::vfs::read(fd, &mut buf)).ok()?;
    let _ = block_on(crate::vfs::close(fd));
    buf.truncate(n);
    String::from_utf8(buf).ok()
}

fn hex_decode(s: &str) -> Option<Vec<u8>> {
    if s.len() % 2 != 0 { return None; }
    let mut out = Vec::with_capacity(s.len() / 2);
    let mut bytes = s.bytes();
    while let (Some(hi), Some(lo)) = (bytes.next(), bytes.next()) {
        out.push(hex_nib(hi)? << 4 | hex_nib(lo)?);
    }
    Some(out)
}

fn hex_nib(c: u8) -> Option<u8> {
    match c {
        b'0'..=b'9' => Some(c - b'0'),
        b'a'..=b'f' => Some(c - b'a' + 10),
        b'A'..=b'F' => Some(c - b'A' + 10),
        _ => None,
    }
}

fn ct_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() { return false; }
    let mut diff: u8 = 0;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}
