#![no_std]

wit_bindgen::generate!({
    path: "../../wit/ruos-bringup.wit",
    world: "bringup",
});

// Minimal bump allocator backing wit-bindgen's cabi_realloc (guest runs once).
use core::alloc::{GlobalAlloc, Layout};
use core::cell::UnsafeCell;
struct Bump { next: UnsafeCell<usize> }
unsafe impl Sync for Bump {}
#[global_allocator]
static A: Bump = Bump { next: UnsafeCell::new(0) };
const HEAP: usize = 1 << 20;
static mut ARENA: [u8; HEAP] = [0; HEAP];
unsafe impl GlobalAlloc for Bump {
    unsafe fn alloc(&self, l: Layout) -> *mut u8 {
        let n = self.next.get();
        let base = core::ptr::addr_of_mut!(ARENA) as usize;
        let cur = (base + *n + l.align() - 1) & !(l.align() - 1);
        let end = cur + l.size();
        if end - base > HEAP { return core::ptr::null_mut(); }
        *n = end - base;
        cur as *mut u8
    }
    unsafe fn dealloc(&self, _: *mut u8, _: Layout) {}
}
#[panic_handler]
fn ph(_: &core::panic::PanicInfo) -> ! { loop {} }

// `Guest` is the trait generated by `generate!` for world `bringup`; our impl
// type must be distinct from it.
struct Component;
export!(Component);

impl Guest for Component {
    fn run() -> i32 {
        // guest -> host string import; the boot test greps this exact marker.
        crate::ruos::bringup::system::log("WT-COMPONENT-OK");
        0
    }
}
